import numpy as np
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
from matplotlib.patches import Patch
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA


def load_and_preprocess():
    """
    Loading the Iris dataset, normalizing the features to [0, 1] range for better SOM training.
    """
    ### IRIS OUT ###
    iris = load_iris()
    X = iris.data.astype(np.float64)
    y = iris.target
    scaler = MinMaxScaler()
    X = scaler.fit_transform(X) # Fit and transform does this: X_scaled = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
    # iris.target_names is the list of class names, like ['setosa', 'versicolor', 'virginica']
    return X, y, iris.target_names 
    

def initialize_weights(grid_x, grid_y, input_dim, seed=42):
    """
    Randomly selecting the initial weights, which represent the prototype vectors for each neuron in the SOM grid.
    """
    rng = np.random.default_rng(seed)
    return rng.random((grid_x, grid_y, input_dim))


def find_bmu(weights, x):
    """
    Best Matching Unit (BMU) is the neuron whose weight vector is closest to the input vector x.
    """
    diff = weights - x
    distances = np.linalg.norm(diff, axis=2) # Norm 2 distance, ie., Euclidean distance
    return np.unravel_index(np.argmin(distances), distances.shape) # oshiete oshieteyo sono shikumi wo


def compute_neighbourhood(grid_x, grid_y, bmu_idx, sigma):
    """
    Compute the value of Neighbourhood for each neuron based on its Euclidean distance to the BMU.
    Neighbourhood function used: Gaussian Function
    """
    bmu_r, bmu_c = bmu_idx
    r = np.arange(grid_x) # r for row
    c = np.arange(grid_y) # c for column
    cc, rr = np.meshgrid(c, r) # som grid 
    d2 = (rr - bmu_r) ** 2 + (cc - bmu_c) ** 2
    return np.exp(-d2 / (2.0 * sigma ** 2))


def update_weights(weights, x, bmu_idx, alpha, sigma):
    """
    WEIGHT UPDATION 🗣️🗣️🗣️🗣️🗣️
    """
    grid_x, grid_y, _ = weights.shape
    h = compute_neighbourhood(grid_x, grid_y, bmu_idx, sigma)
    weights += alpha * h[:, :, np.newaxis] * (x - weights)
    return weights


def decay_parameters(t, n_iterations, alpha_init, sigma_init):
    """
    As the training progresses, both the learning rate (alpha) and the neighbourhood radius (sigma) decay exponentially.
    This allows the SOM to make large adjustments in the early stages and fine-tune in later stages.
    """
    tau = n_iterations
    alpha = alpha_init * np.exp(-t / tau)
    sigma = max(sigma_init * np.exp(-t / tau), 0.5)
    return alpha, sigma


def project_weights_pca(weights, pca):
    """
    Helper function to use PCA on high-D weights for visualization in 2D space.
    """
    gx, gy, d = weights.shape
    return pca.transform(weights.reshape(-1, d)).reshape(gx, gy, 2)

### VISUALIZATION PART, TO BE DONE LATER IN MANIM ###
#### Generated by yours truly, Claude Sonnet 4.6 ####

def plot_som_state(ax, X_pca, y, weights_pca, bmu_idx, x_pca,
                   grid_x, grid_y, h, iteration, alpha, sigma, target_names):
    ax.clear()
    ax.set_facecolor('#1a1a2e')

    palette = ['#e74c3c', '#2ecc71', '#3498db']

    for i in range(grid_x):
        for j in range(grid_y):
            pos = weights_pca[i, j]
            if j + 1 < grid_y:
                nb = weights_pca[i, j + 1]
                ax.plot([pos[0], nb[0]], [pos[1], nb[1]],
                        color='#95a5a6', linewidth=0.7, alpha=0.45, zorder=2)
            if i + 1 < grid_x:
                nb = weights_pca[i + 1, j]
                ax.plot([pos[0], nb[0]], [pos[1], nb[1]],
                        color='#95a5a6', linewidth=0.7, alpha=0.45, zorder=2)

    for cls in range(3):
        mask = y == cls
        ax.scatter(X_pca[mask, 0], X_pca[mask, 1],
                   c=palette[cls], s=22, alpha=0.45, zorder=3,
                   edgecolors='none')

    h_flat = h.flatten()
    h_norm = (h_flat - h_flat.min()) / (h_flat.max() - h_flat.min() + 1e-8)
    neuron_xy = weights_pca.reshape(-1, 2)
    ax.scatter(neuron_xy[:, 0], neuron_xy[:, 1],
               c=h_norm, cmap='plasma', vmin=0.0, vmax=1.0,
               s=55, alpha=0.92, zorder=4,
               edgecolors='white', linewidths=0.4)

    bmu_pos = weights_pca[bmu_idx[0], bmu_idx[1]]
    ax.scatter(bmu_pos[0], bmu_pos[1], c='#f1c40f', s=220,
               marker='*', zorder=6, edgecolors='black', linewidths=1.0)

    ax.scatter(x_pca[0], x_pca[1], c='white', s=130,
               marker='D', zorder=7, edgecolors='black', linewidths=1.5)

    legend_handles = (
        [Patch(facecolor=palette[i], label=target_names[i], alpha=0.8) for i in range(3)] + [
            mlines.Line2D([], [], color='#f1c40f', marker='*', markersize=13,
                          linestyle='None', markeredgecolor='black',
                          markeredgewidth=0.8, label='BMU'),
            mlines.Line2D([], [], color='white', marker='D', markersize=8,
                          linestyle='None', markeredgecolor='black',
                          markeredgewidth=1.2, label='Current sample'),
        ]
    )
    ax.legend(handles=legend_handles, loc='upper right', fontsize=8,
              framealpha=0.3, labelcolor='white', facecolor='#1a1a2e')
    ax.set_title(
        f'SOM Training  |  Iteration {iteration}  |  α = {alpha:.4f}  |  σ = {sigma:.4f}',
        fontsize=10, color='white'
    )
    ax.set_xlabel('PCA Component 1', color='#bdc3c7', fontsize=9)
    ax.set_ylabel('PCA Component 2', color='#bdc3c7', fontsize=9)
    ax.tick_params(colors='#bdc3c7', labelsize=8)
    for spine in ax.spines.values():
        spine.set_edgecolor('#555')


def plot_final_result(X, X_pca, y, weights, pca, grid_x, grid_y, target_names):
    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    fig.patch.set_facecolor('#0f0f1a')
    fig.suptitle('Self-Organizing Map — Final State (Iris Dataset)',
                 fontsize=14, fontweight='bold', color='white')

    palette = ['#e74c3c', '#2ecc71', '#3498db']
    weights_pca = project_weights_pca(weights, pca)

    ax1 = axes[0]
    ax1.set_facecolor('#1a1a2e')

    for i in range(grid_x):
        for j in range(grid_y):
            pos = weights_pca[i, j]
            if j + 1 < grid_y:
                nb = weights_pca[i, j + 1]
                ax1.plot([pos[0], nb[0]], [pos[1], nb[1]],
                         color='#ecf0f1', linewidth=0.9, alpha=0.55, zorder=2)
            if i + 1 < grid_x:
                nb = weights_pca[i + 1, j]
                ax1.plot([pos[0], nb[0]], [pos[1], nb[1]],
                         color='#ecf0f1', linewidth=0.9, alpha=0.55, zorder=2)

    for cls in range(3):
        mask = y == cls
        ax1.scatter(X_pca[mask, 0], X_pca[mask, 1],
                    c=palette[cls], s=35, alpha=0.75, zorder=4,
                    edgecolors='none', label=target_names[cls])

    neuron_xy = weights_pca.reshape(-1, 2)
    ax1.scatter(neuron_xy[:, 0], neuron_xy[:, 1],
                c='#ecf0f1', s=35, alpha=0.9, zorder=3,
                edgecolors='#7f8c8d', linewidths=0.5)

    ax1.legend(fontsize=9, framealpha=0.3, labelcolor='white', facecolor='#1a1a2e')
    ax1.set_title('Final SOM Grid (PCA Projection)', color='white', fontsize=11)
    ax1.set_xlabel('PCA Component 1', color='#bdc3c7', fontsize=9)
    ax1.set_ylabel('PCA Component 2', color='#bdc3c7', fontsize=9)
    ax1.tick_params(colors='#bdc3c7', labelsize=8)
    for spine in ax1.spines.values():
        spine.set_edgecolor('#555')

    ax2 = axes[1]
    ax2.set_facecolor('#1a1a2e')

    bmu_counts = np.zeros((grid_x, grid_y, 3))
    for xi, yi in zip(X, y):
        bmu = find_bmu(weights, xi)
        bmu_counts[bmu[0], bmu[1], yi] += 1

    base_rgb = np.array([
        [231 / 255, 76 / 255, 60 / 255],
        [46 / 255, 204 / 255, 113 / 255],
        [52 / 255, 152 / 255, 219 / 255],
    ])
    bg = np.array([0.12, 0.12, 0.18])

    rgb_map = np.tile(bg, (grid_x, grid_y, 1))
    for i in range(grid_x):
        for j in range(grid_y):
            total = bmu_counts[i, j].sum()
            if total > 0:
                dom = int(np.argmax(bmu_counts[i, j]))
                intensity = float(np.clip(total / 8.0, 0.25, 1.0))
                rgb_map[i, j] = (1.0 - intensity) * bg + intensity * base_rgb[dom]

    ax2.imshow(rgb_map, origin='upper', aspect='equal', interpolation='nearest')

    for i in range(grid_x):
        for j in range(grid_y):
            total = int(bmu_counts[i, j].sum())
            if total > 0:
                ax2.text(j, i, str(total), ha='center', va='center',
                         fontsize=7, color='white', fontweight='bold')

    ax2.set_title('Cluster Map — Dominant Species per Neuron', color='white', fontsize=11)
    ax2.set_xlabel('Grid Column', color='#bdc3c7', fontsize=9)
    ax2.set_ylabel('Grid Row', color='#bdc3c7', fontsize=9)
    ax2.tick_params(colors='#bdc3c7', labelsize=8)
    for spine in ax2.spines.values():
        spine.set_edgecolor('#555')

    legend_handles = [Patch(facecolor=palette[i], label=target_names[i]) for i in range(3)]
    ax2.legend(handles=legend_handles, fontsize=9, framealpha=0.3,
               labelcolor='white', facecolor='#1a1a2e')

    plt.tight_layout()
    plt.show()


def main():
    GRID_X = 10       # SOM Rows
    GRID_Y = 10       # SOM Columns
    N_EPOCHS = 3      # Number of times we go through the entire dataset during training
    ALPHA_INIT = 0.5  # Initial learning rate
    SIGMA_INIT = 5.0  # Initial neighbourhood radius
    VIZ_EVERY = 5     # Visualization frequency (for the matplotlib animation)

    X, y, target_names = load_and_preprocess()
    n_samples, input_dim = X.shape
    n_iterations = N_EPOCHS * n_samples

    pca = PCA(n_components=2) # PCA down to 2D
    pca.fit(X) # Fit PCA on the original data to get the projection matrix, which will be used for both data and weights visualization
    X_pca = pca.transform(X)

    weights = initialize_weights(GRID_X, GRID_Y, input_dim)

    fig, ax = plt.subplots(figsize=(10, 8))
    fig.patch.set_facecolor('#0f0f1a')
    plt.ion()
    plt.show()

    t = 0
    rng = np.random.default_rng(0)
    for epoch in range(N_EPOCHS):
        indices = rng.permutation(n_samples)
        for idx in indices:
            x = X[idx]
            alpha, sigma = decay_parameters(t, n_iterations, ALPHA_INIT, SIGMA_INIT)
            bmu_idx = find_bmu(weights, x)

            if t % VIZ_EVERY == 0:
                h = compute_neighbourhood(GRID_X, GRID_Y, bmu_idx, sigma)
                weights_pca = project_weights_pca(weights, pca)
                x_pca = pca.transform(x.reshape(1, -1))[0]
                plot_som_state(ax, X_pca, y, weights_pca, bmu_idx, x_pca,
                               GRID_X, GRID_Y, h, t, alpha, sigma, target_names)
                fig.canvas.draw()
                plt.pause(0.125)

            weights = update_weights(weights, x, bmu_idx, alpha, sigma)
            t += 1

    plt.ioff()
    plt.close(fig)

    plot_final_result(X, X_pca, y, weights, pca, GRID_X, GRID_Y, target_names)


if __name__ == '__main__':
    main()
